"""Generate public Apps Script schema/prompt/policy from merged Python sources."""
import ast
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
# Execute only schema declarations: no provider imports, credentials or API calls.
tree = ast.parse((root / 'src/scoring.py').read_text(encoding='utf-8'))
nodes = [n for n in tree.body if isinstance(n, (ast.Assign, ast.FunctionDef))
         and not (isinstance(n, ast.FunctionDef) and n.name == 'assess')]
namespace = {}
exec(compile(ast.Module(body=nodes, type_ignores=[]), '<schema>', 'exec'), namespace)
constants = {
    'AI_SCORING_SCHEMA': namespace['SCHEMA'],
    'AI_SCORING_PROMPT': (root / 'prompts/fit_evaluation.md').read_text(encoding='utf-8'),
    'AI_SCORING_POLICY': json.loads((root / 'context/policy.json').read_text(encoding='utf-8')),
}
(root.parent / 'collector/ScoringConfig.gs').write_text(
    '// Generated by scripts/sync_apps_script_scoring.py. No private sources.\n'
    + '\n'.join('const ' + key + ' = ' + json.dumps(value, ensure_ascii=False, indent=2) + ';'
                for key, value in constants.items()) + '\n', encoding='utf-8')

import shutil
shutil.copy2(root.parent / "collector/ScoringConfig.gs", root / "apps-script/ScoringConfig.gs")
