const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const context=vm.createContext({console});
for(const file of ['ScoringConfig.gs','Scoring.gs']) vm.runInContext(fs.readFileSync('apps-script/'+file,'utf8'),context);
vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8'),context);
function run(code) {return vm.runInContext(code,context);}
assert.equal(run("canonical('http://jobs.lever.co/acme/id/apply?utm_source=x#top')"),'https://jobs.lever.co/acme/id');
assert.equal(run("vacancyId('https://boards.greenhouse.io/acme/jobs/123?gh_src=x')"),'greenhouse:123');
assert.equal(run("vacancyId('https://jobs.lever.co/acme/abc/apply')"),'lever:abc');
assert.equal(run("vacancyId('https://company.example/careers?gh_jid=42')"),'greenhouse:42');
assert.equal(run("trackerKeys([['Unternehmen','Position','Quelle','Status'],['Acme','Head of Operations','https://jobs.lever.co/acme/abc/apply','Applied']]).has('lever:abc')"),true);
assert.equal(run("trackerKeys([['Company','Role','Source','Status'],['Acme','Head of Operations','','Rejected']]).has('role:acme|head of operations')"),true);
assert.throws(()=>run("trackerKeys([['Company','Role','Status']])"),/headers/);
assert.throws(()=>run("trackerKeys([['Company','Role','Source','Status'],['Acme','','','Applied']])"),/Incomplete/);
run("var sample={company:'Acme',title:'Head of Operations',location:'Berlin, Germany',description:'English-speaking team'};");
assert.equal(run('eligible(sample)'),true);
assert.equal(run("eligible(Object.assign({},sample,{title:'Junior Operations Manager'}))"),false);
assert.equal(run("eligible(Object.assign({},sample,{location:'Remote US only'}))"),false);
assert.equal(run("eligible(Object.assign({},sample,{location:'Remote Europe'}))"),true);
assert.equal(run("eligible(Object.assign({},sample,{description:'Must be fluent in German'}))"),false);
assert.equal(run("eligible(Object.assign({},sample,{description:'German is a plus'}))"),true);
assert.equal(run("jobFrom({id:1,internal_job_id:null},BOARDS[0])"),null);
assert.equal(run("jobFrom({isListed:false},{provider:'ashby'})"),null);
run("var ashbyRaw={isListed:true,title:'Head of Operations',jobUrl:'https://jobs.ashbyhq.com/acme/abc',location:'Berlin',isRemote:false,descriptionPlain:'A'.repeat(250)}; var ashbyBoard={provider:'ashby',board:'acme',company:'Acme'};");
assert.equal(run('jobFrom(ashbyRaw,ashbyBoard).id'),'abc');
run("var realDiscover=discover;discover=()=>[jobFrom(ashbyRaw,ashbyBoard)];");
assert.equal(run('validate(jobFrom(ashbyRaw,ashbyBoard),{}).id'),'abc');
run('discover=()=>[];');
assert.equal(run('validate(jobFrom(ashbyRaw,ashbyBoard),{})'),null);
run('discover=realDiscover;');
assert.equal(run("eligible(Object.assign({},sample,{location:'Remote Worldwide'}))"),true);
assert.equal(run("eligible(Object.assign({},sample,{location:'Remote United States'}))"),false);
run(`var realFetch=fetchResponse;var fetchedUrls=[];fetchResponse=url=>{fetchedUrls.push(url);return {getContentText:()=>JSON.stringify({'job-count':1,jobs:[{id:7,company_name:'Acme',title:'Head of Operations',url:'https://remotive.com/remote-jobs/business/head-7',candidate_required_location:'Worldwide',description:'A'.repeat(250)}]})};};`);
assert.equal(run('discoverFeed(DISCOVERY_SOURCES[0]).jobs[0].employer_live_verified'),false);
assert.equal(run('discoverFeed(DISCOVERY_SOURCES[0]).jobs[0].source'),'Remotive');
run(`fetchResponse=url=>({getContentText:()=>JSON.stringify({data:[],meta:{current_page:Number(url.split('=').pop())},links:{next:'https://evil.example/next'}})});`);
assert.throws(()=>run('discoverFeed(DISCOVERY_SOURCES[1])'),/Unexpected/);
run(`var crawlPages=[];var endPage=100;fetchResponse=url=>{const p=Number(url.split('=').pop());crawlPages.push(p);return {getContentText:()=>JSON.stringify({data:[],meta:{current_page:p},links:{next:p<endPage?'https://www.arbeitnow.com/api/job-board-api?page='+(p+1):null}})};}; var resume={next_page:11,cycles_completed:0};var crawlOne=discoverFeed(DISCOVERY_SOURCES[1],resume);`);
assert.deepEqual(JSON.parse(run('JSON.stringify(crawlPages)')),[1,2,3,10,11,12,13,14,15,16]);
assert.equal(run('crawlOne.checkpoint.next_page'),17);
assert.equal(run('resume.next_page'),11);
run('crawlPages=[];var crawlTwo=discoverFeed(DISCOVERY_SOURCES[1],crawlOne.checkpoint);');
assert.deepEqual(JSON.parse(run('JSON.stringify(crawlPages)')),[1,2,3,16,17,18,19,20,21,22]);
run('crawlPages=[];endPage=12;var crawlEnd=discoverFeed(DISCOVERY_SOURCES[1],resume);');
assert.equal(run('crawlEnd.cycle_finished'),true);
assert.equal(run('crawlEnd.checkpoint.next_page'),4);
assert.equal(run('crawlEnd.checkpoint.cycles_completed'),1);
run('crawlPages=[];var nextCycle=discoverFeed(DISCOVERY_SOURCES[1],crawlEnd.checkpoint);');
assert.deepEqual(JSON.parse(run('JSON.stringify(crawlPages)')),[1,2,3,4,5,6,7,8,9,10]);
run('fetchResponse=()=>{throw new Error("Temporary outage");};');
assert.throws(()=>run('discoverFeed(DISCOVERY_SOURCES[1],resume)'),/outage/);
assert.equal(run('resume.next_page'),11);
run(`fetchResponse=()=>({getContentText:()=>JSON.stringify({jobs:[],jobCount:0,hasMore:true,nextCursor:'repeat'})});`);
assert.throws(()=>run('discoverFeed(DISCOVERY_SOURCES[2])'),/cursor/);
assert.equal(run("boardFromUrl('https://jobs.ashbyhq.com/newco/abc','NewCo').board"),'newco');
assert.equal(run("boardFromUrl('https://jobs.ashbyhq.com.evil.example/newco/abc','NewCo')"),null);
run(`var realFeed=discoverFeed;discoverFeed=s=>({jobs:[leadFrom({id:7,company_name:'Acme',title:'Head of Operations',url:'https://remotive.com/remote-jobs/business/head-7',candidate_required_location:'Worldwide',description:'A'.repeat(250)},DISCOVERY_SOURCES[0])],pages:1,truncated:false});`);
assert.equal(run("marketDiscovery(new Set(['role:acme|head of operations']),{},{discovered_boards:[]}).leads.length"),0);
assert.equal(run("marketDiscovery(new Set(),{},{discovered_boards:[]}).leads.length"),1);
run(`var learnedState={};discoverFeed=s=>({jobs:[leadFrom({id:8,company_name:'NewCo',title:'Head of Operations',url:'https://remotive.com/remote-jobs/business/head-8',candidate_required_location:'Worldwide',description:'<a href="https://jobs.ashbyhq.com/newco/abc">Apply</a>'+ 'A'.repeat(250)},DISCOVERY_SOURCES[0])],pages:1,truncated:false});marketDiscovery(new Set(),{},learnedState);`);
assert.equal(run('learnedState.discovered_boards.length'),1);
assert.equal(run("learnedState.discovered_boards[0].board"),'newco');
run(`discoverFeed=realFeed;var pageCounter=0;fetchResponse=()=>({getContentText:()=>JSON.stringify({jobs:[],jobCount:0,hasMore:true,nextCursor:'cursor'+(++pageCounter)})});`);
assert.equal(run("discoverFeed(Object.assign({},DISCOVERY_SOURCES[2],{max_pages:2})).truncated"),true);
assert.equal(run('pageCounter'),2);
run(`fetchResponse=()=>{throw new Error('Provider unavailable');};`);
assert.equal(run('marketDiscovery(new Set(),{},{discovered_boards:[]}).errors.length'),3);
run('discoverFeed=realFeed;fetchResponse=realFetch;');
run(`var retainedMarket=marketDiscovery, savedOutputFiles=outputFiles, savedGoogleRequest=googleRequest;
outputFiles=(f,n)=>[{id:n}];googleRequest=url=>({getContentText:()=>JSON.stringify(url.includes('processed_jobs.json')?{version:1,processed:{}}:{discovery_sources:[{source:'Arbeitnow',pages:10,truncated:true}],discovery_leads:[{provider:'remotive',id:'7',company:'Acme',title:'Head of Operations',url:'https://remotive.com/remote-jobs/business/head-7',location:'Remote Worldwide',description:'A'.repeat(250),requires_employer_verification:true}]})});
var migrated=readState({OUTPUT_FOLDER_ID:'fixture'});outputFiles=savedOutputFiles;googleRequest=savedGoogleRequest;
discoverFeed=()=>({jobs:[],pages:1,truncated:false});var retained=marketDiscovery(new Set(),{},migrated);`);
assert.equal(run('migrated.feed_progress.arbeitnow.next_page'),11);
assert.equal(run('retained.leads.length'),1);
assert.equal(run('retained.leads[0].employer_live_verified'),false);
run("marketDiscovery(new Set(['role:acme|head of operations']),{},migrated);");
assert.equal(run('Object.keys(migrated.discovery_review).length'),0);
run('discoverFeed=realFeed;');
assert.equal(run("plain('<p>Operations &amp; Strategy</p>')"),'Operations & Strategy');

console.log('PASS: legacy feeds, Arbeitnow resume, discovery queue and source migrations');

assert.deepEqual(JSON.parse(run('JSON.stringify(BOARDS)')),JSON.parse(fs.readFileSync('context/apps_script_boards.json','utf8')));
require('./apps_script_rotation.test.cjs');
require('./apps_script_providers.test.cjs');
require('./apps_script_scoring.test.cjs');

require('./apps_script_diagnostics.test.cjs');
require('./apps_script_recovery.test.cjs');
