export const STATUSES = ['To review', 'Shortlisted', 'Applied', 'Interview', 'Rejected', 'Withdrawn', 'Offer'];
export function safeUrl(value) {try {const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}}
export function canonicalUrl(value) {const url=safeUrl(value);if(!url)return '';const u=new URL(url);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_/i.test(k)||['source','ref','gh_src','pid','language','lever-source','trackingId'].includes(k))u.searchParams.delete(k);u.pathname=u.pathname.replace(/\/(apply|application)\/?$/,'').replace(/\/$/,'');u.searchParams.sort();return u.href;}
export function jobKey(job) {const url=canonicalUrl(job.url);if(url)return url;return `role:${String(job.company||'').toLowerCase().trim()}|${String(job.title||'').toLowerCase().trim()}`;}
export function normalizeJob(raw) {if(!raw||typeof raw!=='object'||!String(raw.title||'').trim())throw new Error('Each role needs a title.');const url=safeUrl(raw.url||'');if(raw.url&&!url)throw new Error('Only ordinary http(s) job links are supported.');return {company:String(raw.company||'Unknown company').slice(0,300),title:String(raw.title).slice(0,500),location:String(raw.location||'Not specified').slice(0,500),url,description:String(raw.description||raw.text||'').slice(0,100000),provider:String(raw.provider||raw.board?.provider||'manual'),live_checked_at:typeof raw.live_checked_at==='string'?raw.live_checked_at:null,employer_live_verified:raw.employer_live_verified===true,requires_employer_verification:raw.requires_employer_verification===true,scoring:raw.scoring&&typeof raw.scoring==='object'?JSON.parse(JSON.stringify(raw.scoring)):null,demo:raw.demo===true};}
export function mergeJobs(existing,incoming) {const byKey=new Map(existing.map(j=>[jobKey(j),j]));for(const raw of incoming){const job=normalizeJob(raw),key=jobKey(job),old=byKey.get(key);byKey.set(key,{...job,id:key,status:old?.status||'To review',notes:old?.notes||'',added_at:old?.added_at||new Date().toISOString(),updated_at:new Date().toISOString()});}return [...byKey.values()];}
export function importPacket(packet) {if(!packet||typeof packet!=='object'||!Array.isArray(packet.candidates))throw new Error('Choose candidates.json from the collector.');if(packet.candidates.length>5000)throw new Error('The report contains too many roles.');return {jobs:packet.candidates.map(raw=>normalizeJob({...raw,demo:false})),coverage:{checked_at:packet.checked_at||null,version:packet.collector_version||'legacy',attempted:packet.company_boards??null,configured:packet.total_company_boards??null,completed:packet.board_coverage?.boards_completed_this_run??null,unavailable:packet.board_coverage?.unavailable_this_run?.length??null,inventory:Array.isArray(packet.board_coverage?.inventory)?packet.board_coverage.inventory.slice(0,5000):[]}};}
export function toCsv(jobs) {const value=v=>'"'+String(v??'').replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"';return [['Company','Role title','Location','Source','Status','Notes','Added date'],...jobs.filter(j=>!j.demo).map(j=>[j.company,j.title,j.location,j.url,j.status,j.notes,j.added_at])].map(row=>row.map(value).join(',')).join('\r\n');}
export function parseCsv(text) {const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw new Error('The CSV contains an unclosed quote.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
export function importTracker(text,existing) {const rows=parseCsv(text);const index=rows.findIndex(row=>row.some(c=>/^(company|unternehmen)$/i.test(c.trim())));if(index<0)throw new Error('Tracker CSV needs Company, Role title and Status columns.');const headers=rows[index].map(c=>c.trim().toLowerCase());const col=aliases=>headers.findIndex(c=>aliases.includes(c));const ci=col(['company','unternehmen']),ti=col(['role title','role','position']),ui=col(['source','url','quelle','job url']),si=col(['status']),ni=col(['notes','note']);if(ci<0||ti<0||si<0)throw new Error('Tracker columns were not recognised.');let output=existing.slice();for(const row of rows.slice(index+1)){if(!row[ci]||!row[ti])continue;const incoming=normalizeJob({company:row[ci],title:row[ti],url:ui<0?'':row[ui]});const key=jobKey(incoming);let job=output.find(j=>jobKey(j)===key);if(!job&&!incoming.url){const matches=output.filter(j=>j.company.toLowerCase()===incoming.company.toLowerCase()&&j.title.toLowerCase()===incoming.title.toLowerCase());if(matches.length===1)job=matches[0];}if(!job){job={...incoming,id:key,added_at:new Date().toISOString()};output.push(job);}job.status=STATUSES.find(s=>s.toLowerCase()===String(row[si]).trim().toLowerCase())||'To review';job.notes=ni>=0?String(row[ni]||''):job.notes||'';}return output;}
