import {evaluateJob} from '../../core/evaluate.js';
import {STATUSES,jobKey,mergeJobs,importPacket,toCsv,importTracker,normalizeJob,safeUrl} from '../../core/jobs.js';
import {createStorage,emptyWorkspace,WORKSPACE_KEY} from '../../core/storage.js';
import {buildCandidateProfile,loadCandidateProfile,PROFILE_STORAGE_KEY} from '../extension/src/profile/profile-settings.js';
const $=id=>document.getElementById(id),storage=createStorage();
let workspace=emptyWorkspace(),settings=null,demo=null,filter='All';
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
const activeJobs=()=>demo?demo.jobs:workspace.jobs;
const activeSettings=()=>demo?demo.profile:settings;
let profile=null;
async function refreshProfile(){profile=demo?buildCandidateProfile(demo.profile):globalThis.chrome?.storage?.local?(await loadCandidateProfile(chrome)).profile:buildCandidateProfile(settings);}
const evaluate=job=>evaluateJob(job,profile,{configured:!!activeSettings()?.configured});
function notify(message,error=false){$('notice').textContent=message;$('notice').className='notice'+(error?' error':'');$('notice').hidden=false;}
async function persist(){if(!demo)await storage.write(WORKSPACE_KEY,workspace);render();}
function render(){const jobs=activeJobs();$('setup-banner').hidden=!!activeSettings()?.configured;$('total-count').textContent=jobs.length;$('list-count').textContent=jobs.length;for(const [id,status] of [['review-count','To review'],['applied-count','Applied'],['interview-count','Interview']])$(id).textContent=jobs.filter(j=>j.status===status).length;$('demo-button').textContent=demo?'Exit demo':'Try the demo';const query=$('search').value.toLowerCase();const visible=jobs.filter(j=>(filter==='All'||j.status===filter||evaluate(j).verdict===filter)&&[j.title,j.company,j.location].join(' ').toLowerCase().includes(query));$('jobs').replaceChildren();$('empty').hidden=visible.length>0;for(const job of visible){const result=evaluate(job),row=element('button',undefined,'job-row');row.type='button';row.append(element('span',job.company.replace(/[^a-z]/gi,'').slice(0,2).toUpperCase(),'company-icon'));const text=element('div',undefined,'job-text');text.append(element('h3',job.title),element('p',`${job.company} · ${job.location}`));const outcome=element('div',undefined,'job-result');outcome.append(element('span',result.verdict,'badge '+result.verdict.toLowerCase()),element('small',result.score===null?'Needs verification':`${result.score}/100 · triage`));row.append(text,outcome,element('span',job.status,'status-label'),element('span','›','chevron'));row.addEventListener('click',()=>showDetail(job));$('jobs').append(row);}}
function box(title,values){const section=element('section',undefined,'detail-box');section.append(element('h3',title));if(Array.isArray(values)){const list=element('ul');values.forEach(v=>list.append(element('li',typeof v==='string'?v:v.reason||v.label||String(v))));section.append(list);}else section.append(element('p',values));return section;}
function showDetail(job){const result=evaluate(job),content=$('detail-content');content.replaceChildren();const heading=element('div',undefined,'dialog-heading'),close=element('button','×','close');close.type='button';close.addEventListener('click',()=>$('detail-dialog').close());heading.append(element('h2',job.title),close);content.append(heading,element('p',`${job.company} · ${job.location}`,'detail-company'));const summary=element('div',undefined,'detail-summary');summary.append(element('span',result.verdict,'badge '+result.verdict.toLowerCase()),element('p',result.score===null?'Review blocked':`${result.score}/100 preliminary triage. Evidence confidence has not been assessed.`));content.append(summary,box('Review',result.explanation));if(result.strongestMatches?.length)content.append(box('Relevant signals',result.strongestMatches));if(result.keyGaps?.length)content.append(box('Questions to resolve',result.keyGaps));if(result.blockers?.length)content.append(box('Conflicts',result.blockers));if(safeUrl(job.url)){const link=element('a',job.demo?'Fictional example link':'Open original posting ↗','button secondary');link.href=safeUrl(job.url);link.target='_blank';link.rel='noopener noreferrer';content.append(link);}
if(!job.demo&&!result.live_verified){const label=element('label',undefined,'check'),check=element('input');check.type='checkbox';label.append(check,element('span','I checked the original employer posting and it is accepting applications now.'));check.addEventListener('change',async()=>{if(!check.checked)return;job.employer_live_verified=true;job.requires_employer_verification=false;job.live_checked_at=new Date().toISOString();await persist();showDetail(job);});content.append(label);}
if(job.scoring){content.append(box('Imported evidence assessment',`Decision: ${job.scoring.decision||'not supplied'} · Score: ${job.scoring.score??'?'} · Confidence: ${job.scoring.confidence??'?'} · Assessed: ${job.scoring.assessed_at||'not supplied'}. This assessment belongs to the collector’s private source profile. Recheck it against your current evidence; it is separate from the local triage signal.`));if(job.scoring.questions?.length)content.append(box('Imported evidence questions',job.scoring.questions));}
content.append(box('Your decision','The signal is advisory. Review required evidence before applying. Changing a status never sends an application.'));const statusLabel=element('label','Application status'),select=element('select');for(const value of STATUSES){const option=element('option',value);option.value=value;select.append(option);}select.value=job.status;select.addEventListener('change',async()=>{job.status=select.value;await persist();});statusLabel.append(select);const noteLabel=element('label','Your notes'),notes=element('textarea');notes.value=job.notes||'';notes.placeholder='Evidence gaps, follow-up, interview notes…';notes.addEventListener('change',async()=>{job.notes=notes.value;await persist();});noteLabel.append(notes);content.append(statusLabel,noteLabel);const jd=element('details',undefined,'detail-box');jd.append(element('summary','Full job description'),element('div',job.description||'No description imported.','jd'));content.append(jd);if(!$('detail-dialog').open)$('detail-dialog').showModal();}
async function toggleDemo(){if(demo){demo=null;notify('Back in your own workspace.');}else{const response=await fetch('../../examples/demo.json');if(!response.ok)throw new Error('Could not load the demo.');const packet=await response.json();demo={profile:packet.profile,jobs:mergeJobs([],packet.candidates)};notify('Demo mode: all companies and roles are fictional. Changes here do not affect your workspace.');}await refreshProfile();render();}
const fields=['targetRoles','potentialRoles','skipRoles','preferredLocations','preferredSeniority','verifiedLanguages','unavailableLanguages','strengths'];
function showProfile(){if(demo){notify('Exit the demo to edit your own profile.');return;}for(const name of fields)$('profile-form').elements[name].value=(settings?.[name]||[]).join(', ');$('advanced-profile').hidden=!globalThis.chrome?.storage?.local;$('profile-dialog').showModal();}
function leaveDemo(){if(demo){demo=null;return refreshProfile();}return Promise.resolve();}
function download(content,name,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type})),link=element('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function guard(fn){return async(...args)=>{try{await fn(...args);}catch(error){notify(error.message||'Something went wrong.',true);}};}
for(const id of ['demo-button','empty-demo'])$(id).addEventListener('click',guard(toggleDemo));for(const id of ['profile-nav','profile-button','setup-button'])$(id).addEventListener('click',showProfile);
$('opportunities-nav').addEventListener('click',()=>{document.querySelector('.list-section').scrollIntoView({behavior:'smooth'});});
$('profile-form').addEventListener('submit',guard(async event=>{event.preventDefault();const previous=settings||{};settings={...previous,configured:true};for(const name of fields)settings[name]=[...new Set($('profile-form').elements[name].value.split(',').map(v=>v.trim()).filter(Boolean))];await storage.write(PROFILE_STORAGE_KEY,settings);await refreshProfile();$('profile-dialog').close();notify('Your profile is saved. All roles have been reviewed again.');render();}));
$('advanced-profile').addEventListener('click',()=>{const link=chrome.runtime.getURL('apps/extension/src/options/options.html');chrome.tabs.create({url:link});});
$('add-button').addEventListener('click',guard(async()=>{await leaveDemo();$('add-form').reset();$('add-dialog').showModal();render();}));
$('add-form').addEventListener('submit',guard(async event=>{event.preventDefault();const form=new FormData(event.target),checked=form.has('verified'),job=normalizeJob(Object.fromEntries(form));job.employer_live_verified=checked;job.live_checked_at=checked?new Date().toISOString():null;job.requires_employer_verification=!checked;workspace.jobs=mergeJobs(workspace.jobs,[job]);await persist();$('add-dialog').close();notify('Opportunity added. You decide the next step.');}));
for(const button of document.querySelectorAll('[data-close]'))button.addEventListener('click',()=>button.closest('dialog').close());
for(const button of document.querySelectorAll('[data-filter]'))button.addEventListener('click',()=>{filter=button.dataset.filter;for(const other of document.querySelectorAll('[data-filter]'))other.classList.toggle('selected',other===button);render();});$('search').addEventListener('input',render);
for(const [button,input] of [['import-button','file-input'],['tracker-import-button','tracker-input'],['restore-button','restore-input']])$(button).addEventListener('click',()=>$(input).click());
async function readFile(input){const file=input.files[0];if(!file)return null;if(file.size>20*1024*1024)throw new Error('Choose a file smaller than 20 MB.');const text=await file.text();input.value='';return text;}
$('file-input').addEventListener('change',guard(async()=>{const text=await readFile($('file-input'));if(text===null)return;const packet=importPacket(JSON.parse(text));await leaveDemo();workspace.jobs=mergeJobs(workspace.jobs,packet.jobs);workspace.coverage=packet.coverage;await persist();notify(`Imported ${packet.jobs.length} roles. Existing statuses and notes were preserved.`);}));
$('tracker-input').addEventListener('change',guard(async()=>{const text=await readFile($('tracker-input'));if(text===null)return;const jobs=importTracker(text,workspace.jobs);await leaveDemo();workspace.jobs=jobs;await persist();notify('Tracker imported. Matched roles retain their full job descriptions.');}));
$('csv-button').addEventListener('click',()=>{if(demo)return notify('Exit the demo to export your own tracker.');download(toCsv(workspace.jobs),'jobops-tracker.csv','text/csv;charset=utf-8');});
$('backup-button').addEventListener('click',()=>download(JSON.stringify({version:1,profile:settings,workspace},null,2),'jobops-backup.json'));
$('restore-input').addEventListener('change',guard(async()=>{const text=await readFile($('restore-input'));if(text===null)return;const data=JSON.parse(text);if(data.version!==1||!Array.isArray(data.workspace?.jobs)||data.workspace.jobs.length>5000)throw new Error('Choose a JobOps version 1 backup.');if(data.profile&&(!data.profile.configured||fields.some(name=>data.profile[name]&&!Array.isArray(data.profile[name]))))throw new Error('The backup profile is invalid.');const incoming=data.workspace.jobs.map(raw=>({...normalizeJob({...raw,demo:false}),status:STATUSES.includes(raw.status)?raw.status:'To review',notes:String(raw.notes||'').slice(0,100000),added_at:raw.added_at}));await leaveDemo();workspace.jobs=mergeJobs(workspace.jobs,incoming);for(const raw of incoming){const job=workspace.jobs.find(j=>jobKey(j)===jobKey(raw));if(job){job.status=raw.status;job.notes=raw.notes;}}workspace.coverage=data.workspace.coverage||workspace.coverage;if(data.profile){settings=data.profile;await storage.write(PROFILE_STORAGE_KEY,settings);}await refreshProfile();await persist();notify('Backup restored and merged with your workspace.');}));
$('sources-nav').addEventListener('click',()=>{const coverage=workspace.coverage,content=$('coverage-content');content.replaceChildren();if(!coverage){content.append(element('p','Import candidates.json from the collector to see actual source coverage. The public board audit is a dated snapshot, not proof that a posting is open today.','muted'));}else{content.append(box('Latest imported report',`Checked: ${coverage.checked_at||'Not supplied'} · Attempted: ${coverage.attempted??'?'} / ${coverage.configured??'?'} · Completed: ${coverage.completed??'?'} · Unavailable: ${coverage.unavailable??'?'}`),element('p','Attempted boards are not completed boards. Sources without a recent successful check need complementary employer verification.','muted'));const list=element('ul',undefined,'coverage-list');for(const board of Array.isArray(coverage.inventory)?coverage.inventory:[]){const item=element('li',`${board.company||board.key} · ${board.provider||''} · ${board.status||board.audit_status||'not checked'} · Last completion: ${board.last_success_at||'never'}`);if(safeUrl(board.web_fallback_url)){const link=element('a',' Employer careers ↗');link.href=safeUrl(board.web_fallback_url);link.target='_blank';link.rel='noopener noreferrer';item.append(link);}list.append(item);}content.append(list);}$('coverage-dialog').showModal();});
try{const saved=await storage.read(WORKSPACE_KEY);if(saved?.version===1&&Array.isArray(saved.jobs))workspace=saved;settings=await storage.read(PROFILE_STORAGE_KEY);await refreshProfile();render();}catch(error){notify('Could not load local data: '+error.message,true);}
